language: cpp
compiler:
  - g++
# Change this to your needs
install:
- sudo apt-get install libprotobuf-dev libboost-all-dev
- sudo apt-get install libgflags-dev libgoogle-glog-dev protobuf-compiler

script:
- make test
- ./tests/test