language: cpp
compiler:
  - g++
# Change this to your needs
install:
- sudo apt-get install libprotobuf-dev libboost-all-dev
- sudo apt-get install libgflags-dev libgoogle-glog-dev protobuf-compiler

#before_script: 
#- cd externals/OpenBLAS
#- make
#- cd ../../

script:
- make test
- ./tests/test