notifications:
email: 
recipients:
- shubhamg@stanford.edu
- chrismre@stanford.edu
- fabuzaid@stanford.edu
- czhang@cs.wisc.edu
on_failure: change

language: cpp
compiler:
  - g++
# Change this to your needs
before_install:
# - travis_retry git submodule update
- travis_retry sudo apt-get update
- travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- travis_retry sudo apt-get -qq update
- travis_retry sudo apt-get -qq install g++-4.8
- travis_retry sudo apt-get install libgtest-dev
- "pushd .; git clone git://git.openldap.org/openldap.git && cd openldap/libraries/liblmdb && make && sudo make install; cd -; popd"
- sudo apt-get install gfortran
- "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- "wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz && tar zxvf glog-0.3.3.tar.gz && cd glog-0.3.3 &&  ./configure && make && sudo make install; cd -"
- "pushd .; wget https://github.com/schuhschuh/gflags/archive/master.zip && unzip master.zip && cd gflags-master && mkdir build && cd build && export CXXFLAGS=\"-fPIC\" && cmake .. && make VERBOSE=1 && make && sudo make install; popd"

install:
- "cd ./externals/OpenBLAS && sudo make -Wno- -s > /dev/null && sudo make install PREFIX=/usr/local ; cd -"
- sudo apt-get install libprotobuf-dev libboost-all-dev
- sudo apt-get install protobuf-compiler

cache:
apt: true
directories:
- ./externals/OpenBLAS
- /usr/src/gtest
- /usr/local/lib

script:
- "cp config.travis .config"
- make test
- ./test
