notifications:
email: 
recipients:
- chrismre@stanford.edu
- fabuzaid@stanford.edu
- czhang@cs.wisc.edu
on_failure: change

language: cpp
compiler:
  - g++
# Change this to your needs
before_install:
- travis_retry sudo apt-get update
- travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- travis_retry sudo apt-get -qq update
- travis_retry sudo apt-get -qq install g++-4.8
- travis_retry sudo apt-get install libblas-dev
- travis_retry sudo apt-get install libgtest-dev
- "pushd .; git clone git://git.openldap.org/openldap.git && cd openldap/libraries/liblmdb && make && sudo make install; cd -; popd"

install:
- sudo apt-get install libprotobuf-dev libboost-all-dev
- sudo apt-get install protobuf-compiler

cache:
apt: true
directories:
- /usr/src/gtest
- /usr/local/lib

script:
- "cp config.travis .config"
- make test
- ./test
