notifications:
email: false

language: cpp
compiler:
  - g++
# Change this to your needs
install:
- sudo apt-get install libprotobuf-dev libboost-all-dev
- sudo apt-get install protobuf-compiler
- sudo apt-get install libgtest0 libgtest-dev

script:
- make test
- ./test