notifications:
email: 
recipients:
- shubhamg@stanford.edu
- chrismre@stanford.edu
- fabuzaid@stanford.edu
on_failure: change

language: cpp
compiler:
  - g++
# Change this to your needs
before_install:
- sudo apt-get update
- sudo apt-get install libgtest-dev
- sudo apt-get install gfortran
- "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- "cd /usr/src/gtest && ls"
- git submodule update
- "cd ./externals/OpenBLAS && sudo make -Wno- -s > /dev/null && sudo make install PREFIX= ./externals/OpenBLAS; cd -"
install:
- sudo apt-get install libprotobuf-dev libboost-all-dev
- sudo apt-get install protobuf-compiler

cache:
apt: true
directories:
- ./externals/OpenBLAS
- /usr/src/gtest
- /usr/local/lib

script:
- "cp config.travis .config"
- make test
- ./test
